# -*- coding: utf-8 -*-
"""OpenAIExtractor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YOSkkpNsQ8arMSFldQtBLVBvvDwYU3TI
"""

pip install openai

import os
import openai
openai.organization = "org-zPrvVu8wSB03buxCiZpm7qoh"
openai.api_key = "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"
#openai.Model.list()

toParse = '''Festivals and Events
DesignTO Festival
Supported by: Government of Ontario, Ontario Arts Council and Google.
Celebrating art and design across the city with over 100 exhibitions and events, bringing people together to design a future that is more sustainable, just, and joyful.
AccessibleFree EventArts/Exhibits, Talks, Virtual/Online Event

When: January 20, 2023 - January 29, 2023

Where: Toronto
online and in-person

Cost: Free
Most events and exhibitions are free, but some require a RSVP or purchased tickets. Please visit website for more information.

Reservations / Advance Tickets are required
Online: designto.org
More Information
Website: designto.org?'''

openai.Completion.create(
  model="text-davinci-003",
  prompt='''can you extract information summarize the following input into a json format like this:
   "title": "event 2",
   "description": "death",
   "location": "my hall",
   "_type": "competition",
   "startDate": "2023-01-21",
   "endDate": "2023-01-25",
   "registrationReq": false,
   "frequency": "yearly"''' + toParse,
  max_tokens=1000,
  temperature=0
)