# Generated by Django 4.1.5 on 2023-01-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventsite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="frequency",
            field=models.CharField(default="one_time", max_length=30),
            preserve_default=False,
        ),
    ]
